name: Install dependencies and run tests

on:
  push:
    branches:
      - develop
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Run tests
      run: |
        pytest || python -m unittest discover
